# Join CombLeerdoelOpleidingsniveau → leerplan → Leerplan
SELECT DISTINCT ?CombLeerdoelOpleidingsniveau_url ?Leerplan_url WHERE {
  ?CombLeerdoelOpleidingsniveau_url a <http://example.com/EigenCombinatieLeerdoelOpleidingsniveau> .
  ?Leerplan_url a <http://example.com/Leerplan> .
  ?CombLeerdoelOpleidingsniveau_url <http://example.com/leerplan> ?Leerplan_url .
}
