# Join Licentie → type → OnderwerpType
SELECT DISTINCT ?Licentie_url ?OnderwerpType_url WHERE {
  ?Licentie_url a <http://purl.org/dc/terms/LicenseDocument> .
  ?OnderwerpType_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?Licentie_url <http://purl.org/dc/terms/type> ?OnderwerpType_url .
}
