# Join Doel → eigenCombinatieLeerdoelOpleidingsniveau → CombLeerdoelOpleidingsniveau
SELECT DISTINCT ?Doel_url ?CombLeerdoelOpleidingsniveau_url WHERE {
  ?Doel_url a <http://data.europa.eu/snb/model/elm/LearningAchievement> .
  ?CombLeerdoelOpleidingsniveau_url a <http://example.com/EigenCombinatieLeerdoelOpleidingsniveau> .
  ?Doel_url <http://example.com/eigenCombinatieLeerdoelOpleidingsniveau> ?CombLeerdoelOpleidingsniveau_url .
}
