# Join Doelgroep → leeftijdstype → OnderwerpType
SELECT DISTINCT ?Doelgroep_url ?OnderwerpType_url WHERE {
  ?Doelgroep_url a <https://schema.org/Audience> .
  ?OnderwerpType_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?Doelgroep_url <http://purl.org/dc/terms/type> ?OnderwerpType_url .
}
